service: backend

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.spell_check
    events:
      - http:
          path: spellcheck
          method: post

plugins:
  - serverless-offline
custom:
  # Puerto del serverless
  serverlessoffline:
    httpPort: 4000
