service: backend

provider:
  name: aws
  runtime: python3.8

functions:
  spellpost:
    # El handler es la función "lambda" que estaría en AWS, en este caso la función tiene la capacidad
    # De cambiar su respuesta si recibe un post o un get
    handler: handler.spell_check
    events:
      - httpApi: "post spellcheck"
  spellget:
    handler: handler.get_from_database
    events:
      - http: "get spellcheck"
      
      

plugins:
  - serverless-offline
